# Generated by Django 5.2.5 on 2025-08-07 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=155, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='utopia_realty_app.city')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlanValue',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=20)),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='utopia_realty_app.paymentplan')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('external_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover', models.URLField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_date', models.DateField()),
                ('low_price', models.BigIntegerField(blank=True, null=True)),
                ('min_area', models.IntegerField(blank=True, null=True)),
                ('payment_plan', models.BooleanField(default=False)),
                ('post_delivery', models.BooleanField(default=False)),
                ('payment_minimum_down_payment', models.PositiveIntegerField()),
                ('guarantee_rental_guarantee', models.BooleanField(default=False)),
                ('guarantee_rental_guarantee_value', models.PositiveIntegerField()),
                ('down_payment', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='utopia_realty_app.city')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='utopia_realty_app.developer')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='utopia_realty_app.district')),
                ('facilities', models.ManyToManyField(related_name='properties', to='utopia_realty_app.facility')),
                ('property_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='utopia_realty_app.propertystatus')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='utopia_realty_app.propertytype')),
                ('sales_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='utopia_realty_app.salesstatus')),
            ],
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='utopia_realty_app.property'),
        ),
        migrations.CreateModel(
            name='GroupedApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(blank=True, max_length=255, null=True)),
                ('rooms', models.PositiveIntegerField()),
                ('min_price', models.PositiveIntegerField()),
                ('min_area', models.PositiveIntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouped_apartments', to='utopia_realty_app.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utopia_realty_app.facility')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utopia_realty_app.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('image', models.URLField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='utopia_realty_app.property')),
            ],
        ),
    ]
