# Generated by Django 5.2.5 on 2025-08-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utopia_realty_app', '0002_alter_facility_id_alter_groupedapartment_min_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupedapartment',
            name='rooms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
