# Generated by Django 5.2.5 on 2025-08-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utopia_realty_app', '0003_alter_groupedapartment_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
